### ISSUE TITLE
calculate and store all stats as per game-prototype

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#482]
## Relevant Goals
- !Learner stats match our subjective reality, elicit honest feedback, and promote self-directed, collaborative growth
- !Players know how to increase low stats
## Prototype
- Calculate and store project stats (mimic the [project-stats](https://github.com/LearnersGuild/game-prototype/blob/master/bin/project-stats) script from `game-prototype`)
- Calculate and store review stats (mimic the [review-stats](https://github.com/LearnersGuild/game-prototype/blob/master/bin/review-stats) script from `game-prototype`)
- Calculate and store aggregate stats (mimic the [stat-report-chapter](https://github.com/LearnersGuild/game-prototype/blob/master/bin/stat-report-chapter) script from `game-prototype`)
### Stat data schema

**For each player in each project**
- [x] `cycle_no` (not a stat!)
- [x] `project_id` (not a stat!)
- [x] `player_id` (not a stat!)
- [x] `xp`
- [x] `proj_hours` (`hours`)
- [x] `health_culture` (`cc`)
- [x] `health_team_play` (`tp`)
- [x] `health_technical` (`th`)
- [x] `challenge`
- [x] `project_contrib` (`rc`)
- [x] `expected_contrib` (`ec`)
- [ ] `est_accuracy`
- [ ] `est_bias`
- [x] `elo_before` (we store the current rating with the stats for each project)
- [x] `elo_after` (we store the current rating with the stats for each project)
- [x] `computed_at` (when the stats calculation was performed)

**For all projects with reviews**
- [x] `cycle_no` (not a stat)
- [x] `project_id` (not a stat)
- [ ] `avg_completeness`
- [ ] `avg_quality`

**Aggregate stats for each player**
- [x] `player_id` (not a stat!)
- [x] `xp`
- [x] `avg_cycle_hours` (avg last 6 cycles)
- [x] `health_culture` (avg last 6 cycles)
- [x] `health_team_play` (avg last 6 cycles)
- [x] `health_technical` (avg last 6 cycles)
- [x] `challenge` (avg last 6 cycles)
- [ ] `est_accuracy` (avg last 6 cycles)
- [ ] `est_bias` (avg last 6 cycles)
- [ ] `avg_proj_comp` (avg last 6 cycles)
- [ ] `avg_proj_qual` (avg last 6 cycles)
- [ ] `no_proj_rvws`
- [x] `elo`
- [x] `computed_at` (when the last stats calculation was performed)
