### ISSUE TITLE
when a cycle changes states from `GOAL_SELECTION` to `PRACTICE`, Projects will be created

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#63]
## Requirements
- players must be in same chapter
- team size (aim for 4)
- channel created for each project
  - named: `<random-word>-<goal-number>` (obviously de-duplicated)
  - players assigned to projects are automatically invited to the project channel in chat, using welcome message
    - `lg-bot` sends welcome message to project and chapter channels with:
      - notify player @handles, "Welcome to #channel_name. Here is your [goal](#)."
    - don't automatically add users to the room
## Tasks
- [x] figure out dictionary of random words to use
- [x] API to launch a cycle
  - [x] moderators table (associated with chapter)
- [ ] model Projects
  - has one goal
  - has a start time
  - has a duration (# of cycles)
  - has many players (**NOTE:** players can change at cycle boundary)
  - `channelName` (`<adjective>-<animal>-<goalIssueNumber>`)
- [x] changefeed to listen for cycle state changes (kick-off a background job to create Project)
  - [x] create Project and assign Players (MVP: shuffle all chapter onto top N projects)
  - [x] [create Project channel in chat](https://github.com/RocketChat/Rocket.Chat/blob/develop/server/restapi/restapi.coffee#L198)
    - [x] ensure that we have a Rocket.Chat API user with `adminautomation` role
  - [x] [notify Players in chapter and project channels in chat](https://github.com/RocketChat/Rocket.Chat/blob/develop/server/restapi/restapi.coffee#L53-L58)
    - [x] API to send message using `channelName`
