### ISSUE TITLE
server/db eliminated

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#973]
From [ch1657](https://app.clubhouse.io/learnersguild/story/1657)

This was originally a task in story #1472.

---

Background:
https://learnersguild-hub.slack.com/files/jeffrey/F4KKY33S6/LOS_Gaps__Q2_focus_

Overview:
Core business logic is tightly coupled to db CRUD logic. It's in our best interest to more cleanly separate/organize it. Everything currently in `server/db` should go to one of these new places:

- ported over to using Thinky models (`server/services/dataService`)
- moved into a standalone `server/action` function
- moved into a `dataService` query
### Tasks

- [x] relocate `db/chapter` logic
- [x] relocate `db/cycle` logic
- [x] relocate `db/moderator` logic
- [x] relocate `db/player` logic
- [x] relocate `db/pool` logic
- [x] relocate `db/project` logic
- [x] relocate `db/question` logic
- [x] relocate `db/response` logic
- [x] relocate `db/stat` logic
- [x] relocate `db/survey` logic
- [x] relocate `db/surveyBlueprint` logic
- [x] relocate `db/vote` logic
- [x] relocate `db/errors` logic
- [x] relocate `db/util` logic

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: doesn't this depend on ch1546? To truly eliminate `server/db`, won't we need many-to-many stuff working?

**Comment by jeffreywescott** [comment]
**[Comment from Clubhouse user @prattsj:]** We can get rid of `server/db` logic without porting everything over to Thinky that could possibly be moved. If there's anything in `server/db` that requires a many-to-many relationship in the model, it's probably logic that's complex enough that it belongs wrapped up in a server action anyway, so we can keep the implementation as it is (using the rethinkdb client directly), move it out of `server/db` and into a server action, and later revisit with a repo-wide sweep in the work for ch1546.

**Comment by prattsj** [comment]
Already complete.
